FROM python:3.14-alpine

RUN apk update && apk add gcc musl-dev python3-dev libffi-dev openssl-dev --no-cache

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY payloads/ .
COPY static/ .
COPY templates/ .
COPY *.py ./
COPY csp.txt .

RUN "python" "db_init.py"

USER nobody

EXPOSE 8080

CMD [ "python", "./vulpy.py" ]
