name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: VaultVulp/action-pipenv@v1.0.0
        with:
          args: "install -d check"
      - uses: jpetrucciani/bandit-check@1.6.2
      - name: build Docker
        run: docker build . -t benno001/problematic-project
      - name: Dockle
        run: |
          export DOCKLE_LATEST=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/' \
            )
          docker run --rm goodwithtech/dockle:v${DOCKLE_LATEST} benno001/problematic-project:latest
      - name: Bandit Check
        
