name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: VaultVulp/action-pipenv@v1.0.0
        with:
          args: "install -d"
      - uses: VaultVulp/action-pipenv@v1.0.0
        with:
          args: "check"
      - name: Bandit Check
        uses: jpetrucciani/bandit-check@1.6.2
      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.0.2    
        
